// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateTrackPoints implements pgx.CopyFromSource.
type iteratorForCreateTrackPoints struct {
	rows                 []CreateTrackPointsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTrackPoints) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTrackPoints) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Time,
		r.rows[0].ContainerID,
		r.rows[0].Lat,
		r.rows[0].Lon,
		r.rows[0].Speed,
	}, nil
}

func (r iteratorForCreateTrackPoints) Err() error {
	return nil
}

// Bulk insert via pgx.CopyFrom (bypass sqlc for performance)
func (q *Queries) CreateTrackPoints(ctx context.Context, arg []CreateTrackPointsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"track_points"}, []string{"time", "container_id", "lat", "lon", "speed"}, &iteratorForCreateTrackPoints{rows: arg})
}
