// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package consumer

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Container struct {
	ID            pgtype.UUID
	ContainerID   string
	Owner         pgtype.Text
	ContainerType pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

type TrackPoint struct {
	Time        pgtype.Timestamptz
	ContainerID string
	Lat         float64
	Lon         float64
	Speed       pgtype.Float8
}

type TrackPointsHourly struct {
	Bucket      interface{}
	ContainerID string
	PointCount  int64
	AvgSpeed    float64
	MaxSpeed    interface{}
	RouteLine   interface{}
}
