// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreateTrackPointsParams struct {
	Time        pgtype.Timestamptz
	ContainerID string
	Lat         float64
	Lon         float64
	Speed       pgtype.Float8
}

const getContainerRoute = `-- name: GetContainerRoute :many
SELECT time,
    lat,
    lon,
    speed
FROM track_points
WHERE container_id = $1
    AND time BETWEEN $2 AND $3
ORDER BY time
`

type GetContainerRouteParams struct {
	ContainerID string
	Time        pgtype.Timestamptz
	Time_2      pgtype.Timestamptz
}

type GetContainerRouteRow struct {
	Time  pgtype.Timestamptz
	Lat   float64
	Lon   float64
	Speed pgtype.Float8
}

// Container route for time range (draw polyline)
func (q *Queries) GetContainerRoute(ctx context.Context, arg GetContainerRouteParams) ([]GetContainerRouteRow, error) {
	rows, err := q.db.Query(ctx, getContainerRoute, arg.ContainerID, arg.Time, arg.Time_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContainerRouteRow
	for rows.Next() {
		var i GetContainerRouteRow
		if err := rows.Scan(
			&i.Time,
			&i.Lat,
			&i.Lon,
			&i.Speed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestPositions = `-- name: GetLatestPositions :many
SELECT DISTINCT ON (container_id) container_id,
    time,
    lat,
    lon,
    speed
FROM track_points
WHERE time > NOW() - INTERVAL '1 hour'
ORDER BY container_id,
    time DESC
`

type GetLatestPositionsRow struct {
	ContainerID string
	Time        pgtype.Timestamptz
	Lat         float64
	Lon         float64
	Speed       pgtype.Float8
}

// Latest position per container (map markers)
func (q *Queries) GetLatestPositions(ctx context.Context) ([]GetLatestPositionsRow, error) {
	rows, err := q.db.Query(ctx, getLatestPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestPositionsRow
	for rows.Next() {
		var i GetLatestPositionsRow
		if err := rows.Scan(
			&i.ContainerID,
			&i.Time,
			&i.Lat,
			&i.Lon,
			&i.Speed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
