// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Geofence struct {
	ID        pgtype.UUID
	Name      string
	OwnerID   string
	Boundary  string
	Enabled   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type GeofenceState struct {
	ContainerID string
	GeofenceID  pgtype.UUID
	Inside      bool
	UpdatedAt   pgtype.Timestamptz
}
