// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findContainingGeofences = `-- name: FindContainingGeofences :many
SELECT id, name, owner_id
FROM geofences
WHERE enabled = TRUE
  AND ST_Contains(boundary, ST_SetSRID(ST_MakePoint($1, $2), 4326))
`

type FindContainingGeofencesParams struct {
	StMakepoint   interface{}
	StMakepoint_2 interface{}
}

type FindContainingGeofencesRow struct {
	ID      pgtype.UUID
	Name    string
	OwnerID string
}

// Find all enabled geofences containing a given point
// $1 = longitude, $2 = latitude (PostGIS ST_MakePoint takes x,y = lon,lat)
func (q *Queries) FindContainingGeofences(ctx context.Context, arg FindContainingGeofencesParams) ([]FindContainingGeofencesRow, error) {
	rows, err := q.db.Query(ctx, findContainingGeofences, arg.StMakepoint, arg.StMakepoint_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindContainingGeofencesRow
	for rows.Next() {
		var i FindContainingGeofencesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInsideStates = `-- name: GetInsideStates :many
SELECT gs.geofence_id, g.name, g.owner_id
FROM geofence_states gs
JOIN geofences g ON g.id = gs.geofence_id
WHERE gs.container_id = $1
  AND gs.inside = TRUE
  AND g.enabled = TRUE
`

type GetInsideStatesRow struct {
	GeofenceID pgtype.UUID
	Name       string
	OwnerID    string
}

// All geofences where a container is currently "inside" (for EXIT detection)
func (q *Queries) GetInsideStates(ctx context.Context, containerID string) ([]GetInsideStatesRow, error) {
	rows, err := q.db.Query(ctx, getInsideStates, containerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInsideStatesRow
	for rows.Next() {
		var i GetInsideStatesRow
		if err := rows.Scan(&i.GeofenceID, &i.Name, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getState = `-- name: GetState :one
SELECT inside, updated_at
FROM geofence_states
WHERE container_id = $1
  AND geofence_id = $2
`

type GetStateParams struct {
	ContainerID string
	GeofenceID  pgtype.UUID
}

type GetStateRow struct {
	Inside    bool
	UpdatedAt pgtype.Timestamptz
}

// Get current state for a (container, geofence) pair
func (q *Queries) GetState(ctx context.Context, arg GetStateParams) (GetStateRow, error) {
	row := q.db.QueryRow(ctx, getState, arg.ContainerID, arg.GeofenceID)
	var i GetStateRow
	err := row.Scan(&i.Inside, &i.UpdatedAt)
	return i, err
}

const upsertState = `-- name: UpsertState :exec
INSERT INTO geofence_states (container_id, geofence_id, inside, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (container_id, geofence_id)
DO UPDATE SET inside = $3, updated_at = NOW()
`

type UpsertStateParams struct {
	ContainerID string
	GeofenceID  pgtype.UUID
	Inside      bool
}

// Supabase: data-upsert — atomic INSERT ... ON CONFLICT, no race condition
func (q *Queries) UpsertState(ctx context.Context, arg UpsertStateParams) error {
	_, err := q.db.Exec(ctx, upsertState, arg.ContainerID, arg.GeofenceID, arg.Inside)
	return err
}
