// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailHistory struct {
	ID             pgtype.UUID
	ContainerID    string
	GeofenceName   string
	EventType      string
	RecipientEmail string
	Subject        string
	SentAt         pgtype.Timestamptz
}

type NotificationRecipient struct {
	ID        pgtype.UUID
	OwnerID   string
	Email     string
	Name      string
	Enabled   bool
	CreatedAt pgtype.Timestamptz
}
