// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getRecipientsByOwner = `-- name: GetRecipientsByOwner :many
SELECT email, name FROM notification_recipients
WHERE owner_id = $1 AND enabled = TRUE
`

type GetRecipientsByOwnerRow struct {
	Email string
	Name  string
}

func (q *Queries) GetRecipientsByOwner(ctx context.Context, ownerID string) ([]GetRecipientsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, getRecipientsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipientsByOwnerRow
	for rows.Next() {
		var i GetRecipientsByOwnerRow
		if err := rows.Scan(&i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEmail = `-- name: RecordEmail :exec
INSERT INTO email_history (container_id, geofence_name, event_type, recipient_email, subject)
VALUES ($1, $2, $3, $4, $5)
`

type RecordEmailParams struct {
	ContainerID    string
	GeofenceName   string
	EventType      string
	RecipientEmail string
	Subject        string
}

func (q *Queries) RecordEmail(ctx context.Context, arg RecordEmailParams) error {
	_, err := q.db.Exec(ctx, recordEmail,
		arg.ContainerID,
		arg.GeofenceName,
		arg.EventType,
		arg.RecipientEmail,
		arg.Subject,
	)
	return err
}
