apiVersion: batch/v1
kind: Job
metadata:
  name: notification-migrate-${VERSION}
  namespace: app
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: migrate/migrate:v4.17.0
        args:
          - "-path=/migrations"
          - "-database=$(DATABASE_URL)"
          - "up"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: notification-db-app
              key: uri
        volumeMounts:
        - name: migrations
          mountPath: /migrations
      volumes:
      - name: migrations
        configMap:
          name: notification-migrations
